# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school_setting', '0001_initial'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamHallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExamModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(blank=True, choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('exam', 'EXAM'), ('assessment', 'ASSESSMENT'), ('assignment', 'ASSIGNMENT')], max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('mark', models.FloatField()),
                ('question_type', models.CharField(choices=[('objective', 'OBJECTIVE'), ('subjective', 'SUBJECTIVE'), ('theory', 'THEORY'), ('practical', 'PRACTICAL')], max_length=20)),
                ('subjective_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('theory_answer', models.TextField(blank=True, null=True)),
                ('is_sub', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestionOptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbering', models.CharField(max_length=10)),
                ('option', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory_answer', models.TextField(blank=True, null=True)),
                ('subjective_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('correct_answer', models.BooleanField(blank=True, null=True)),
                ('marked', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExamTimeTableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('exam_type', models.CharField(blank=True, choices=[('objective', 'OBJECTIVE'), ('theory', 'THEORY'), ('practical', 'PRACTICAL'), ('combined', 'COMBINED')], max_length=10, null=True)),
                ('exam_mode', models.CharField(blank=True, choices=[('online', 'ONLINE'), ('paper/pen', 'PAPER/PEN'), ('combined', 'COMBINED')], default='paper/pen', max_length=10, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
                ('class_section', models.ManyToManyField(blank=True, to='academic.classsectionmodel')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='exam.exammodel')),
                ('session', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel')),
                ('student_class', models.ManyToManyField(blank=True, to='academic.classesmodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectsmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExamSittingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sit_number', models.CharField(max_length=100)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exammodel')),
            ],
        ),
    ]
