# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
        ('school_setting', '0001_initial'),
        ('student', '0001_initial'),
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsittingmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='examsittingmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exammodel'),
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='objective_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.examquestionoptionmodel'),
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examquestionmodel'),
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='examresultmodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='examquestionoptionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='examquestionmodel',
            name='correct_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correct_answer', to='exam.examquestionoptionmodel'),
        ),
        migrations.AddField(
            model_name='examquestionmodel',
            name='options',
            field=models.ManyToManyField(blank=True, to='exam.examquestionoptionmodel'),
        ),
        migrations.AddField(
            model_name='examquestionmodel',
            name='sub_questions',
            field=models.ManyToManyField(blank=True, to='exam.examquestionmodel'),
        ),
        migrations.AddField(
            model_name='examquestionmodel',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.examtimetablemodel'),
        ),
        migrations.AddField(
            model_name='examquestionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='session',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classsectioninfomodel'),
        ),
        migrations.AddField(
            model_name='exammodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
