# Generated by Django 4.1.7 on 2023-04-30 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PositionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/staff_images')),
                ('residential_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('staff_id', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_date', models.DateTimeField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='staff/cv')),
                ('salary', models.BigIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('referral_fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('referral_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('referral_address', models.CharField(blank=True, max_length=200, null=True)),
                ('referral_office', models.TextField(blank=True, max_length=200, null=True)),
                ('referral_image', models.FileField(blank=True, null=True, upload_to='staff/referral')),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('genotype', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('section', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.departmentmodel')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='human_resource.positionmodel')),
            ],
        ),
        migrations.AddConstraint(
            model_name='staffmodel',
            constraint=models.UniqueConstraint(fields=('staff_id',), name='unique_staff_id'),
        ),
        migrations.AddConstraint(
            model_name='departmentmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_dept_name_type_combo'),
        ),
    ]
