# Generated by Django 4.2.1 on 2023-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrsettingmodel',
            name='auto_generate_staff_id',
            field=models.BooleanField(default=True),
        ),
    ]
