# Generated by Django 4.2.1 on 2023-08-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('maintenance', 'MAINTENANCE')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FrontEndSetting',
        ),
    ]
