# Generated by Django 4.2.1 on 2023-08-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0002_frontendsettingmodel_delete_frontendsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='auxiliary_color',
            field=models.CharField(default='aa', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='main_color',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
