# Generated by Django 4.2.1 on 2023-08-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0003_frontendsettingmodel_auxiliary_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontEndPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='active_pages',
            field=models.ManyToManyField(blank=True, to='front_cms.frontendpages'),
        ),
    ]
