# Generated by Django 4.2.1 on 2023-08-03 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('front_cms', '0004_frontendpages_frontendsettingmodel_active_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='type',
            field=models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='frontendsettingmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
