# Generated by Django 4.2.1 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0005_frontendsettingmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontendsettingmodel',
            name='auxiliary_color',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='frontendsettingmodel',
            name='main_color',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
