# Generated by Django 4.2.1 on 2023-08-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0007_frontslidermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontslidermodel',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
