# Generated by Django 4.2.1 on 2023-08-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_cms', '0008_alter_frontslidermodel_button_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontslidermodel',
            name='second_image',
            field=models.FileField(blank=True, null=True, upload_to='frontend/slider'),
        ),
        migrations.AlterField(
            model_name='frontslidermodel',
            name='button_link',
            field=models.CharField(blank=True, choices=[('homepage', 'HOME PAGE'), ('about', 'ABOUT'), ('contact_us', 'CONTACT'), ('gallery', 'GALLERY'), ('staff', 'OUR STAFF')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='frontslidermodel',
            name='status',
            field=models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20),
        ),
    ]
