# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0003_initial'),
        ('school_utility', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelroommodel',
            name='assistant_room_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_room_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='class_section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_hostel', to='school_utility.hostelmodel'),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='room_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_room_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelroommodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='assistant_hostel_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_hostel_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='class_section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='hostel_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelbedmodel',
            name='hostel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_hostel', to='school_utility.hostelmodel'),
        ),
        migrations.AddField(
            model_name='hostelbedmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_room', to='school_utility.hostelroommodel'),
        ),
        migrations.AddField(
            model_name='hostelbedmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hostel_bed_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hostelbedmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='transportvehiclemodel',
            constraint=models.UniqueConstraint(fields=('vehicle_id', 'type'), name='unique_vehicle_combo'),
        ),
        migrations.AddConstraint(
            model_name='transportroutemodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_transport_route_combo'),
        ),
        migrations.AddConstraint(
            model_name='transportpathmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_transport_path_combo'),
        ),
        migrations.AddConstraint(
            model_name='hostelroommodel',
            constraint=models.UniqueConstraint(fields=('name', 'hostel', 'type'), name='unique_hostel_room_combo'),
        ),
        migrations.AddConstraint(
            model_name='hostelmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_hostel_name_combo'),
        ),
        migrations.AddConstraint(
            model_name='hostelbedmodel',
            constraint=models.UniqueConstraint(fields=('name', 'room', 'hostel', 'type'), name='unique_hostel_bed_combo'),
        ),
    ]
