# Generated by Django 4.1.7 on 2023-04-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.FloatField()),
                ('end_year', models.FloatField()),
                ('delimeter', models.CharField(choices=[('-', '-'), ('/', '/')], max_length=1)),
                ('status', models.CharField(choices=[('a', 'ACTIVE'), ('p', 'PAST'), ('n', 'NEXT')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='mobile_1',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='mobile_2',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='name',
        ),
        migrations.RemoveField(
            model_name='schoolacademicinfomodel',
            name='title',
        ),
        migrations.RemoveField(
            model_name='schoolgeneralinfomodel',
            name='title',
        ),
        migrations.AddField(
            model_name='schoolacademicinfomodel',
            name='next_resumption_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolacademicinfomodel',
            name='term',
            field=models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], default='first', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolgeneralinfomodel',
            name='school_type',
            field=models.CharField(choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'MIXED')], default='mix', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TermRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('1st term', '1st TERM'), ('2nd term', '2nd TERM'), ('3rd term', '3rd TERM')], max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('no_of_students', models.FloatField()),
                ('no_of_staff', models.FloatField()),
                ('no_of_parents', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel')),
            ],
        ),
        migrations.AddField(
            model_name='schoolacademicinfomodel',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='school_setting.sessionmodel'),
            preserve_default=False,
        ),
    ]
