# Generated by Django 4.2.1 on 2023-08-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_setting', '0002_schoolgeneralinfomodel_motto'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolgeneralinfomodel',
            name='website',
            field=models.CharField(default='ww.dklcacademy.com.ng', max_length=200),
            preserve_default=False,
        ),
    ]
