# Generated by Django 4.1.7 on 2023-04-30 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human_resource', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classesmodel',
            name='assistant_class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='assistant_form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_form_teacher', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='classesmodel',
            constraint=models.UniqueConstraint(fields=('name', 'section', 'class_type'), name='unique_name_class_type_combo'),
        ),
    ]
