# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtimetablemodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classtimetablemodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_timetable_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtimetablemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='class_section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='student_class',
            field=models.ManyToManyField(blank=True, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_class_section_info', to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_subject_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionsubjectteachermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
    ]
