# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academic', '0002_initial'),
        ('human_resource', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='assistant_class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='assistant_form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant_form_teacher', to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='class_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_rep', to='student.studentsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='form_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='section',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='student_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='subject_class_info', to='academic.subjectsmodel'),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_section_info_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classsectioninfomodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='promotion_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classesmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='section',
            field=models.ManyToManyField(blank=True, to='academic.classsectionmodel'),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classesmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='active_days',
            field=models.ManyToManyField(blank=True, related_name='active_days', to='academic.daysmodel'),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='head_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='human_resource.staffmodel'),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicsettingmodel',
            name='week_start_day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.daysmodel'),
        ),
        migrations.AddConstraint(
            model_name='subjectsmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_subject_name_type_combo', violation_error_message='Subject Already Exists'),
        ),
        migrations.AddConstraint(
            model_name='classsectionmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_class_name_type_combo', violation_error_message='Class Section Already Exists'),
        ),
        migrations.AddConstraint(
            model_name='classsectioninfomodel',
            constraint=models.UniqueConstraint(fields=('student_class', 'section', 'type'), name='unique_student_class_section_combo'),
        ),
        migrations.AddConstraint(
            model_name='classesmodel',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_class_type_combo'),
        ),
    ]
