# Generated by Django 4.2.1 on 2023-08-01 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_remove_lessondocumentmodel_class_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonnotemodel',
            name='grant_access',
            field=models.BooleanField(default=False),
        ),
    ]
