# Generated by Django 4.2.1 on 2023-08-20 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_inventorystockmodel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystockmodel',
            name='date',
            field=models.DateField(blank=True, default=datetime.date(2023, 8, 20)),
        ),
        migrations.AlterField(
            model_name='inventorystockoutmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 8, 20)),
        ),
        migrations.AlterField(
            model_name='inventorystockoutsummarymodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 8, 20)),
        ),
    ]
