# Generated by Django 4.2.1 on 2023-07-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_save_sent_message', models.BooleanField(default=False)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FrontDeskInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_days', models.CharField(blank=True, max_length=255, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('sms_type', models.CharField(blank=True, choices=[('plain', 'PLAIN'), ('multimedia', 'MULTIMEDIA')], default='active', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='communication/message')),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryFollowUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('query_type', models.CharField(blank=True, choices=[('plain', 'PLAIN'), ('multimedia', 'MULTIMEDIA')], default='active', max_length=20)),
                ('flow', models.CharField(blank=True, choices=[('incoming', 'INCOMING'), ('outgoing', 'OUTGOING')], max_length=20)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('query_type', models.CharField(blank=True, choices=[('plain', 'PLAIN'), ('multimedia', 'MULTIMEDIA')], default='active', max_length=20)),
                ('flow', models.CharField(blank=True, choices=[('incoming', 'INCOMING'), ('outgoing', 'OUTGOING')], max_length=20)),
                ('recipient', models.CharField(blank=True, choices=[('student', 'STUDENT'), ('staff', 'STAFF'), ('parent', 'PARENT')], max_length=10)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentActivityModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=250)),
                ('reference_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(blank=True, choices=[('1st term', '1st Term'), ('2nd term', '2nd Term'), ('3rd term', '3rd Term')], max_length=20)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY'), ('mix', 'GENERAL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SentMessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(choices=[('sms', 'SMS'), ('email', 'EMAIL')], max_length=50)),
                ('recipients', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SMSConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('africastalking', 'AFRICASTALKING'), ('nexmo', 'NEXMO')], max_length=200)),
                ('api_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SMTPConfigurationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('host', models.CharField(max_length=200)),
                ('port', models.PositiveIntegerField()),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.CharField(blank=True, choices=[('pri', 'PRIMARY'), ('sec', 'SECONDARY')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('visitor_mobile', models.CharField(blank=True, max_length=50)),
                ('purpose', models.CharField(blank=True, max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
                ('sign_in_time', models.TimeField(auto_now_add=True)),
                ('sign_out_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('signed in', 'SIGNED IN'), ('signed out', 'SIGNED OUT')], default='signed in', max_length=20)),
            ],
        ),
    ]
