# Generated by Django 4.1.7 on 2023-04-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_setting', '0002_sessionmodel_remove_schoolacademicinfomodel_email_and_more'),
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'MR'), ('MRS', 'MRS'), ('MISS', 'MISS'), ('MS', 'MS'), ('MAL', 'MAL'), ('DOC', 'DOC'), ('BARR', 'BARR'), ('PST', 'PST'), ('PROF', 'PROF'), ('ENGR', 'ENGR')], max_length=10)),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/parent_images')),
                ('residential_address', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('office_address', models.CharField(blank=True, max_length=200, null=True)),
                ('office_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/student_images')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=20, null=True)),
                ('genotype', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('health_issues', models.TextField(blank=True, null=True)),
                ('relationship_with_parent', models.CharField(choices=[('father', 'FATHER'), ('mother', 'MOTHER'), ('sister', 'SISTER'), ('brother', 'BROTHER'), ('uncle', 'UNCLE'), ('aunty', 'AUNTY'), ('pastor', 'PASTOR'), ('others', 'OTHERS')], max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=15)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student.parentsmodel')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.classesmodel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademicRecordModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_term', models.CharField(max_length=20)),
                ('previous_classes', models.JSONField(blank=True, null=True)),
                ('current_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_current_class', to='academic.classesmodel')),
                ('entry_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.classesmodel')),
                ('entry_session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_setting.sessionmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentsmodel')),
            ],
        ),
    ]
